### ISSUE TITLE
Mac: Unsatisfied requirement (Probably beginner mistake)

### ISSUE THREAD

**Issue by qumusabel** [volatilityfoundation/volatility3#515]
Hello,

I'm trying to analyze macOS memory dump. The banner is `Darwin Kernel Version 16.7.0: Thu Jun 15 17:36:27 PDT 2017; root:xnu-3789.70.16~2/RELEASE_X86_64`, and it is correctly identified. I put `mac.zip` under `volatility3/symbols/`. But 
```
A symbol table requirement was not fulfilled.  Please verify that:
	You have the correct symbol file for the requirement
	The symbol file is under the correct directory or zip file
	The symbol file is named appropriately or contains the correct banner


A translation layer requirement was not fulfilled.  Please verify that:
	A file was provided to create this layer (by -f, --single-location or by config)
	The file exists and is readable
	The necessary symbols are present and identified by volatility3
Unable to validate the plugin requirements: ['plugins.PsList.primary', 'plugins.PsList.darwin']
```
I don't know how to fix this. Currently I'm running is as 
```bash
~/volatility3/vol.py -s ~/volatility3/symbols/ -f ./mem.raw -l log.txt mac.pslist.PsList
```

In `log.txt` volatility correctly identifies the banner, and the symbols for this version seem to be included in `mac.zip`. But then it seeems to just exit out of nowhere, the message is unhelpful. 

```
21-06-06 03:34:55 volatility3.framework.automagic INFO     Running automagic: LayerStacker
21-06-06 03:34:55 volatility3.framework Level 6  Importing from the following paths: /home/user/volatility3/volatility3/framework/layers
21-06-06 03:34:55 volatility3.framework.configuration.requirements Level 9  IndexError - No configuration provided: plugins.PsList.primary
21-06-06 03:34:55 volatility3.framework.configuration.requirements Level 9  Symbol table requirement not yet fulfilled: plugins.PsList.darwin
21-06-06 03:34:56 volatility3.framework.automagic.stacker Level 8  Attempting to stack using LimeStacker
21-06-06 03:34:56 volatility3.framework.automagic.stacker Level 8  Attempting to stack using Elf64Stacker
21-06-06 03:34:56 volatility3.framework.layers.elf Level 6  Exception: Bad magic 0x0 at file offset 0x0
21-06-06 03:34:56 volatility3.framework.automagic.stacker Level 8  Attempting to stack using QemuStacker
21-06-06 03:34:56 volatility3.framework.automagic.stacker Level 8  Attempting to stack using WindowsCrashDumpStacker
21-06-06 03:34:56 volatility3.framework.automagic.stacker Level 8  Attempting to stack using VmwareStacker
21-06-06 03:34:56 volatility3.framework.automagic.stacker Level 8  Attempting to stack using MacIntelStacker
21-06-06 03:34:56 volatility3.framework.automagic.mac DEBUG    Identified banner: b'Darwin Kernel Version 16.7.0: Thu Jun 15 17:36:27 PDT 2017; root:xnu-3789.70.16~2/RELEASE_X86_64\x00'
21-06-06 03:34:56 volatility3.framework.automagic.mac Level 6  Mac find_aslr returned: 0
21-06-06 03:34:56 volatility3.framework.automagic.mac Level 7  Invalid kalsr_shift found at offset: 22607944
21-06-06 03:34:56 volatility3.framework.automagic.mac DEBUG    Identified banner: b'Darwin Kernel Version 16.7.0: Thu Jun 15 17:36:27 PDT 2017; root:xnu-3789.70.16~2/RELEASE_X86_64\x00'
21-06-06 03:34:57 volatility3.framework.automagic.mac Level 6  Mac find_aslr returned: 0
21-06-06 03:34:57 volatility3.framework.automagic.mac Level 7  Invalid kalsr_shift found at offset: 321954688
21-06-06 03:34:57 volatility3.framework.automagic.mac DEBUG    Identified banner: b'Darwin Kernel Version 16.7.0: Thu Jun 15 17:36:27 PDT 2017; root:xnu-3789.70.16~2/RELEASE_X86_64\x00'
21-06-06 03:34:57 volatility3.framework.automagic.mac Level 6  Mac find_aslr returned: 143c6000
21-06-06 03:34:57 volatility3.framework.automagic.stacker Level 7  Exception during stacking: Page Fault at entry 0x0 in table page directory pointer
21-06-06 03:34:57 volatility3.framework.automagic.stacker Level 6  Traceback (most recent call last):

  File "/home/user/volatility3/volatility3/framework/automagic/stacker.py", line 171, in stack_layer
    new_layer = stacker.stack(context, initial_layer, progress_callback)

  File "/home/user/volatility3/volatility3/framework/automagic/mac.py", line 82, in stack
    idlepml4_str = layer.read(idlepml4_ptr, 4)

  File "/home/user/volatility3/volatility3/framework/layers/linear.py", line 37, in read
    for (offset, _, mapped_offset, mapped_length, layer) in self.mapping(offset, length, ignore_errors = pad):

  File "/home/user/volatility3/volatility3/framework/layers/intel.py", line 212, in mapping
    chunk_offset, page_size, layer_name = self._translate(offset)

  File "/home/user/volatility3/volatility3/framework/layers/intel.py", line 105, in _translate
    entry, position = self._translate_entry(offset)

  File "/home/user/volatility3/volatility3/framework/layers/intel.py", line 134, in _translate_entry
    raise exceptions.PagedInvalidAddressException(self.name, offset, position + 1, entry,

volatility3.framework.exceptions.PagedInvalidAddressException: Page Fault at entry 0x0 in table page directory pointer

21-06-06 03:34:57 volatility3.framework.configuration.requirements Level 9  IndexError - No configuration provided: plugins.PsList.primary
21-06-06 03:34:57 volatility3.framework.configuration.requirements Level 9  TypeError - Layer is not the required Architecture: FileLayer
21-06-06 03:34:57 volatility3.framework.automagic.stacker DEBUG    Stacked layers: ['FileLayer']
21-06-06 03:34:57 volatility3.framework.automagic INFO     Running automagic: MacSymbolFinder
21-06-06 03:34:57 volatility3.framework.configuration.requirements Level 9  Symbol table requirement not yet fulfilled: plugins.PsList.darwin
21-06-06 03:34:57 volatility3.framework.configuration.requirements Level 9  IndexError - No configuration provided: plugins.PsList.primary
21-06-06 03:34:57 volatility3.framework.configuration.requirements Level 9  Symbol table requirement not yet fulfilled: plugins.PsList.darwin

``` 

Grepping `isfinfo` for exact build time finds the line.
```
~/volatility3/vol.py -s ~/volatility3/symbols/ -f ./mem.raw -l log.txt isfinfo | grep -a 'Darwin Kernel Version 16.7.0: Thu Jun 15 17:36:27 PDT 2017; root:xnu-3789.70.16~2/RELEASE_X86_64'

jar:file:/home/user/volatility3/symbols/mac.zip!Kernel_Debug_Kit_10.12.6_build_16G29.dmg.json.xz	Unknown	18	4841	43669	164	-	-	Darwin Kernel Version 16.7.0: Thu Jun 15 17:36:27 PDT 2017; root:xnu-3789.70.16~2/RELEASE_X86_64
```

I'm sorry if this is a very beginner question. I'm really at a loss what to do.

**Comment by ikelos** [comment]
Thanks very much for the report.  Hopefully this has been resolved with commit `772083a`.  Please could you test it and let us know if that resolved the issue (and whether the Mac image now reads correctly, or fails to read)?  Thanks...  5:)

**Comment by qumusabel** [comment]
Sorry, this did not fix the issue. The error message is the same.
`log.txt`: 
```
21-06-06 16:06:45 volatility3.cli INFO     Logging started
21-06-06 16:06:45 volatility3.cli INFO     Volatility plugins path: ['/home/user/.local/lib/python3.9/site-packages/volatility3/plugins', '/home/user/.local/lib/python3.9/site-packages/volatility3/framework/plugins']
21-06-06 16:06:45 volatility3.cli INFO     Volatility symbols path: ['/home/user/volatility3/symbols', '/home/user/.local/lib/python3.9/site-packages/volatility3/symbols', '/home/user/.local/lib/python3.9/site-packages/volatility3/framework/symbols']
21-06-06 16:06:45 volatility3.framework Level 6  Importing from the following paths: /home/user/.local/lib/python3.9/site-packages/volatility3/plugins, /home/user/.local/lib/python3.9/site-packages/volatility3/framework/plugins
21-06-06 16:06:45 volatility3.framework Level 6  Importing from the following paths: /home/user/.local/lib/python3.9/site-packages/volatility3/framework/automagic
21-06-06 16:06:45 volatility3.cli Level 7  Cache directory used: /home/user/.cache/volatility3
21-06-06 16:06:45 volatility3.framework.automagic INFO     Detected a mac category plugin
21-06-06 16:06:45 volatility3.framework Level 6  Importing from the following paths: /home/user/.local/lib/python3.9/site-packages/volatility3/framework/layers
21-06-06 16:06:45 volatility3.framework.automagic INFO     Running automagic: ConstructionMagic
21-06-06 16:06:45 volatility3.framework Level 6  Importing from the following paths: /home/user/.local/lib/python3.9/site-packages/volatility3/framework/layers
21-06-06 16:06:45 volatility3.framework.configuration.requirements Level 9  IndexError - No configuration provided: plugins.PsList.primary
21-06-06 16:06:45 volatility3.framework.configuration.requirements Level 9  Symbol table requirement not yet fulfilled: plugins.PsList.darwin
21-06-06 16:06:45 volatility3.framework Level 6  Importing from the following paths: /home/user/.local/lib/python3.9/site-packages/volatility3/framework/layers
21-06-06 16:06:45 volatility3.framework.configuration.requirements Level 9  IndexError - No configuration provided: plugins.PsList.primary
21-06-06 16:06:45 volatility3.framework Level 6  Importing from the following paths: /home/user/.local/lib/python3.9/site-packages/volatility3/framework/layers
21-06-06 16:06:45 volatility3.framework.automagic.construct_layers Level 9  Failed on requirement: plugins.PsList.primary
21-06-06 16:06:45 volatility3.framework.configuration.requirements Level 9  IndexError - No configuration provided: plugins.PsList.primary
21-06-06 16:06:45 volatility3.framework.automagic.construct_layers Level 9  Failed on requirement: plugins.PsList
21-06-06 16:06:45 volatility3.framework Level 6  Importing from the following paths: /home/user/.local/lib/python3.9/site-packages/volatility3/framework/layers
21-06-06 16:06:45 volatility3.framework.configuration.requirements Level 9  Symbol table requirement not yet fulfilled: plugins.PsList.darwin
21-06-06 16:06:45 volatility3.framework Level 6  Importing from the following paths: /home/user/.local/lib/python3.9/site-packages/volatility3/framework/layers
21-06-06 16:06:45 volatility3.framework.automagic.construct_layers Level 9  Failed on requirement: plugins.PsList.darwin
21-06-06 16:06:45 volatility3.framework.configuration.requirements Level 9  Symbol table requirement not yet fulfilled: plugins.PsList.darwin
21-06-06 16:06:45 volatility3.framework.automagic.construct_layers Level 9  Failed on requirement: plugins.PsList
21-06-06 16:06:45 volatility3.framework Level 6  Importing from the following paths: /home/user/.local/lib/python3.9/site-packages/volatility3/framework/layers
21-06-06 16:06:45 volatility3.framework Level 6  Importing from the following paths: /home/user/.local/lib/python3.9/site-packages/volatility3/framework/layers
21-06-06 16:06:45 volatility3.framework Level 6  Importing from the following paths: /home/user/.local/lib/python3.9/site-packages/volatility3/framework/layers
21-06-06 16:06:45 volatility3.framework.automagic.construct_layers Level 6  Construction Exception occurred: Unexpected config value found: None
21-06-06 16:06:45 volatility3.framework.automagic INFO     Running automagic: MacBannerCache
21-06-06 16:06:45 volatility3.framework.symbols.intermed Level 6  Searching for symbols in /home/user/volatility3/symbols, /home/user/.local/lib/python3.9/site-packages/volatility3/symbols, /home/user/.local/lib/python3.9/site-packages/volatility3/framework/symbols
21-06-06 16:06:45 volatility3.framework.automagic INFO     Running automagic: LayerStacker
21-06-06 16:06:45 volatility3.framework Level 6  Importing from the following paths: /home/user/.local/lib/python3.9/site-packages/volatility3/framework/layers
21-06-06 16:06:45 volatility3.framework.configuration.requirements Level 9  IndexError - No configuration provided: plugins.PsList.primary
21-06-06 16:06:45 volatility3.framework.configuration.requirements Level 9  Symbol table requirement not yet fulfilled: plugins.PsList.darwin
21-06-06 16:06:45 volatility3.framework.layers.resources Level 7  Available URL handlers: HTTPErrorProcessor, HTTPDefaultErrorHandler, HTTPRedirectHandler, ProxyHandler, HTTPBasicAuthHandler, ProxyBasicAuthHandler, HTTPDigestAuthHandler, ProxyDigestAuthHandler, AbstractHTTPHandler, HTTPHandler, HTTPSHandler, HTTPCookieProcessor, UnknownHandler, FileHandler, FTPHandler, CacheFTPHandler, DataHandler, VolatilityHandler, JarHandler
21-06-06 16:06:45 volatility3.framework.automagic.stacker Level 8  Attempting to stack using LimeStacker
21-06-06 16:06:45 volatility3.framework.automagic.stacker Level 8  Attempting to stack using Elf64Stacker
21-06-06 16:06:45 volatility3.framework.layers.elf Level 6  Exception: Bad magic 0x0 at file offset 0x0
21-06-06 16:06:45 volatility3.framework.automagic.stacker Level 8  Attempting to stack using QemuStacker
21-06-06 16:06:45 volatility3.framework.automagic.stacker Level 8  Attempting to stack using WindowsCrashDumpStacker
21-06-06 16:06:45 volatility3.framework.automagic.stacker Level 8  Attempting to stack using VmwareStacker
21-06-06 16:06:45 volatility3.framework.automagic.stacker Level 8  Attempting to stack using MacIntelStacker
21-06-06 16:06:45 volatility3.framework.automagic.mac DEBUG    Identified banner: b'Darwin Kernel Version 16.7.0: Thu Jun 15 17:36:27 PDT 2017; root:xnu-3789.70.16~2/RELEASE_X86_64\x00'
21-06-06 16:06:46 volatility3.framework.automagic.mac Level 6  Mac find_aslr returned: 0
21-06-06 16:06:46 volatility3.framework.automagic.mac Level 7  Invalid kalsr_shift found at offset: 22607944
21-06-06 16:06:46 volatility3.framework.automagic.mac DEBUG    Identified banner: b'Darwin Kernel Version 16.7.0: Thu Jun 15 17:36:27 PDT 2017; root:xnu-3789.70.16~2/RELEASE_X86_64\x00'
21-06-06 16:06:47 volatility3.framework.automagic.mac Level 6  Mac find_aslr returned: 0
21-06-06 16:06:47 volatility3.framework.automagic.mac Level 7  Invalid kalsr_shift found at offset: 321954688
21-06-06 16:06:47 volatility3.framework.automagic.mac DEBUG    Identified banner: b'Darwin Kernel Version 16.7.0: Thu Jun 15 17:36:27 PDT 2017; root:xnu-3789.70.16~2/RELEASE_X86_64\x00'
21-06-06 16:06:47 volatility3.framework.automagic.mac Level 6  Mac find_aslr returned: 143c6000
21-06-06 16:06:47 volatility3.framework.automagic.stacker Level 7  Exception during stacking: local variable 'idlepml4_str' referenced before assignment
21-06-06 16:06:47 volatility3.framework.automagic.stacker Level 6  Traceback (most recent call last):

  File "/home/user/.local/lib/python3.9/site-packages/volatility3/framework/automagic/mac.py", line 83, in stack
    idlepml4_str = layer.read(idlepml4_ptr, 4)

  File "/home/user/.local/lib/python3.9/site-packages/volatility3/framework/layers/linear.py", line 37, in read
    for (offset, _, mapped_offset, mapped_length, layer) in self.mapping(offset, length, ignore_errors = pad):

  File "/home/user/.local/lib/python3.9/site-packages/volatility3/framework/layers/intel.py", line 212, in mapping
    chunk_offset, page_size, layer_name = self._translate(offset)

  File "/home/user/.local/lib/python3.9/site-packages/volatility3/framework/layers/intel.py", line 105, in _translate
    entry, position = self._translate_entry(offset)

  File "/home/user/.local/lib/python3.9/site-packages/volatility3/framework/layers/intel.py", line 134, in _translate_entry
    raise exceptions.PagedInvalidAddressException(self.name, offset, position + 1, entry,

volatility3.framework.exceptions.PagedInvalidAddressException: Page Fault at entry 0x0 in table page directory pointer


During handling of the above exception, another exception occurred:


Traceback (most recent call last):

  File "/home/user/.local/lib/python3.9/site-packages/volatility3/framework/automagic/stacker.py", line 171, in stack_layer
    new_layer = stacker.stack(context, initial_layer, progress_callback)

  File "/home/user/.local/lib/python3.9/site-packages/volatility3/framework/automagic/mac.py", line 85, in stack
    vollog.log(constants.LOGLEVEL_VVVV, f"Skipping invalid idlepml4_ptr: 0x{idlepml4_str:0x}")

UnboundLocalError: local variable 'idlepml4_str' referenced before assignment

21-06-06 16:06:47 volatility3.framework.configuration.requirements Level 9  IndexError - No configuration provided: plugins.PsList.primary
21-06-06 16:06:47 volatility3.framework.configuration.requirements Level 9  TypeError - Layer is not the required Architecture: FileLayer
21-06-06 16:06:47 volatility3.framework.automagic.stacker DEBUG    Stacked layers: ['FileLayer']
21-06-06 16:06:47 volatility3.framework.automagic INFO     Running automagic: MacSymbolFinder
21-06-06 16:06:47 volatility3.framework.configuration.requirements Level 9  Symbol table requirement not yet fulfilled: plugins.PsList.darwin
21-06-06 16:06:47 volatility3.framework.configuration.requirements Level 9  IndexError - No configuration provided: plugins.PsList.primary
21-06-06 16:06:47 volatility3.framework.configuration.requirements Level 9  Symbol table requirement not yet fulfilled: plugins.PsList.darwin
```

**Comment by ikelos** [comment]
Ah, my bad.  The errors were actually subtly different.  The second one was because I was using a variable in the error message I added, that didn't exist yet.  5:P  That should now be fixed in `b6165b43`.  It still could do with testing, because I don't know whether simply skipping the bad ones will result in a good one being chosen, but thanks for helping me debug it, the data you attach has just the right amount of information to figure out the problems!  5:D

**Comment by qumusabel** [comment]
Still no success :( Trying pslist and file_list. It now tries to print something, but finds nothing
`log.txt`
```
21-06-07 12:14:41 volatility3.cli INFO     Logging started
21-06-07 12:14:41 volatility3.cli INFO     Volatility plugins path: ['/home/user/.local/lib/python3.9/site-packages/volatility3/plugins', '/home/user/.local/lib/python3.9/site-packages/volatility3/framework/plugins']
21-06-07 12:14:41 volatility3.cli INFO     Volatility symbols path: ['/home/user/volatility3/symbols', '/home/user/.local/lib/python3.9/site-packages/volatility3/symbols', '/home/user/.local/lib/python3.9/site-packages/volatility3/framework/symbols']
21-06-07 12:14:41 volatility3.framework Level 6  Importing from the following paths: /home/user/.local/lib/python3.9/site-packages/volatility3/plugins, /home/user/.local/lib/python3.9/site-packages/volatility3/framework/plugins
21-06-07 12:14:41 volatility3.framework Level 6  Importing from the following paths: /home/user/.local/lib/python3.9/site-packages/volatility3/framework/automagic
21-06-07 12:14:41 volatility3.cli Level 7  Cache directory used: /home/user/.cache/volatility3
21-06-07 12:14:41 volatility3.framework.automagic INFO     Detected a mac category plugin
21-06-07 12:14:41 volatility3.framework Level 6  Importing from the following paths: /home/user/.local/lib/python3.9/site-packages/volatility3/framework/layers
21-06-07 12:14:41 volatility3.framework.automagic INFO     Running automagic: ConstructionMagic
21-06-07 12:14:41 volatility3.framework Level 6  Importing from the following paths: /home/user/.local/lib/python3.9/site-packages/volatility3/framework/layers
21-06-07 12:14:41 volatility3.framework.configuration.requirements Level 9  IndexError - No configuration provided: plugins.List_Files.primary
21-06-07 12:14:41 volatility3.framework.configuration.requirements Level 9  Symbol table requirement not yet fulfilled: plugins.List_Files.darwin
21-06-07 12:14:41 volatility3.framework Level 6  Importing from the following paths: /home/user/.local/lib/python3.9/site-packages/volatility3/framework/layers
21-06-07 12:14:41 volatility3.framework.configuration.requirements Level 9  IndexError - No configuration provided: plugins.List_Files.primary
21-06-07 12:14:41 volatility3.framework Level 6  Importing from the following paths: /home/user/.local/lib/python3.9/site-packages/volatility3/framework/layers
21-06-07 12:14:41 volatility3.framework.automagic.construct_layers Level 9  Failed on requirement: plugins.List_Files.primary
21-06-07 12:14:41 volatility3.framework.configuration.requirements Level 9  IndexError - No configuration provided: plugins.List_Files.primary
21-06-07 12:14:41 volatility3.framework.automagic.construct_layers Level 9  Failed on requirement: plugins.List_Files
21-06-07 12:14:41 volatility3.framework Level 6  Importing from the following paths: /home/user/.local/lib/python3.9/site-packages/volatility3/framework/layers
21-06-07 12:14:41 volatility3.framework.configuration.requirements Level 9  Symbol table requirement not yet fulfilled: plugins.List_Files.darwin
21-06-07 12:14:41 volatility3.framework Level 6  Importing from the following paths: /home/user/.local/lib/python3.9/site-packages/volatility3/framework/layers
21-06-07 12:14:41 volatility3.framework.automagic.construct_layers Level 9  Failed on requirement: plugins.List_Files.darwin
21-06-07 12:14:41 volatility3.framework.configuration.requirements Level 9  Symbol table requirement not yet fulfilled: plugins.List_Files.darwin
21-06-07 12:14:41 volatility3.framework.automagic.construct_layers Level 9  Failed on requirement: plugins.List_Files
21-06-07 12:14:41 volatility3.framework Level 6  Importing from the following paths: /home/user/.local/lib/python3.9/site-packages/volatility3/framework/layers
21-06-07 12:14:41 volatility3.framework.automagic INFO     Running automagic: MacBannerCache
21-06-07 12:14:41 volatility3.framework.symbols.intermed Level 6  Searching for symbols in /home/user/volatility3/symbols, /home/user/.local/lib/python3.9/site-packages/volatility3/symbols, /home/user/.local/lib/python3.9/site-packages/volatility3/framework/symbols
21-06-07 12:14:41 volatility3.framework.automagic INFO     Running automagic: LayerStacker
21-06-07 12:14:41 volatility3.framework Level 6  Importing from the following paths: /home/user/.local/lib/python3.9/site-packages/volatility3/framework/layers
21-06-07 12:14:41 volatility3.framework.configuration.requirements Level 9  IndexError - No configuration provided: plugins.List_Files.primary
21-06-07 12:14:41 volatility3.framework.configuration.requirements Level 9  Symbol table requirement not yet fulfilled: plugins.List_Files.darwin
21-06-07 12:14:41 volatility3.framework.layers.resources Level 7  Available URL handlers: HTTPErrorProcessor, HTTPDefaultErrorHandler, HTTPRedirectHandler, ProxyHandler, HTTPBasicAuthHandler, ProxyBasicAuthHandler, HTTPDigestAuthHandler, ProxyDigestAuthHandler, AbstractHTTPHandler, HTTPHandler, HTTPSHandler, HTTPCookieProcessor, UnknownHandler, FileHandler, FTPHandler, CacheFTPHandler, DataHandler, VolatilityHandler, JarHandler
21-06-07 12:14:41 volatility3.framework.automagic.stacker Level 8  Attempting to stack using LimeStacker
21-06-07 12:14:41 volatility3.framework.automagic.stacker Level 8  Attempting to stack using Elf64Stacker
21-06-07 12:14:41 volatility3.framework.layers.elf Level 6  Exception: Bad magic 0x0 at file offset 0x0
21-06-07 12:14:41 volatility3.framework.automagic.stacker Level 8  Attempting to stack using QemuStacker
21-06-07 12:14:41 volatility3.framework.automagic.stacker Level 8  Attempting to stack using WindowsCrashDumpStacker
21-06-07 12:14:41 volatility3.framework.automagic.stacker Level 8  Attempting to stack using VmwareStacker
21-06-07 12:14:41 volatility3.framework.automagic.stacker Level 8  Attempting to stack using MacIntelStacker
21-06-07 12:14:42 volatility3.framework.automagic.mac DEBUG    Identified banner: b'Darwin Kernel Version 16.7.0: Thu Jun 15 17:36:27 PDT 2017; root:xnu-3789.70.16~2/RELEASE_X86_64\x00'
21-06-07 12:14:43 volatility3.framework.automagic.mac Level 6  Mac find_aslr returned: 0
21-06-07 12:14:43 volatility3.framework.automagic.mac Level 7  Invalid kalsr_shift found at offset: 22607944
21-06-07 12:14:44 volatility3.framework.automagic.mac DEBUG    Identified banner: b'Darwin Kernel Version 16.7.0: Thu Jun 15 17:36:27 PDT 2017; root:xnu-3789.70.16~2/RELEASE_X86_64\x00'
21-06-07 12:14:46 volatility3.framework.automagic.mac Level 6  Mac find_aslr returned: 0
21-06-07 12:14:46 volatility3.framework.automagic.mac Level 7  Invalid kalsr_shift found at offset: 321954688
21-06-07 12:14:46 volatility3.framework.automagic.mac DEBUG    Identified banner: b'Darwin Kernel Version 16.7.0: Thu Jun 15 17:36:27 PDT 2017; root:xnu-3789.70.16~2/RELEASE_X86_64\x00'
21-06-07 12:14:47 volatility3.framework.automagic.mac Level 6  Mac find_aslr returned: 143c6000
21-06-07 12:14:47 volatility3.framework.automagic.mac Level 6  Skipping invalid idlepml4_ptr: 0xffffff8014e516d8
21-06-07 12:14:47 volatility3.framework.automagic.mac DEBUG    Identified banner: b'Darwin Kernel Version 16.7.0: Thu Jun 15 17:36:27 PDT 2017; root:xnu-3789.70.16~2/RELEASE_X86_64\x00'
21-06-07 12:14:49 volatility3.framework.automagic.mac Level 6  Mac find_aslr returned: 15400000
21-06-07 12:14:49 volatility3.framework.automagic.mac DEBUG    DTB was found at: 0x18409000
21-06-07 12:14:49 volatility3.framework.automagic.stacker Level 8  Stacked IntelLayer using MacIntelStacker
21-06-07 12:14:49 volatility3.framework.automagic.stacker Level 8  Attempting to stack using LimeStacker
21-06-07 12:14:49 volatility3.framework.automagic.stacker Level 8  Attempting to stack using Elf64Stacker
21-06-07 12:14:49 volatility3.framework.layers.elf Level 6  Exception: Offset 0x0 does not exist within the base layer
21-06-07 12:14:49 volatility3.framework.automagic.stacker Level 8  Attempting to stack using QemuStacker
21-06-07 12:14:49 volatility3.framework.automagic.stacker Level 8  Attempting to stack using WindowsCrashDumpStacker
21-06-07 12:14:49 volatility3.framework.automagic.stacker Level 8  Attempting to stack using VmwareStacker
21-06-07 12:14:49 volatility3.framework.configuration.requirements Level 9  IndexError - No configuration provided: plugins.List_Files.primary
21-06-07 12:14:49 volatility3.framework Level 6  Importing from the following paths: /home/user/.local/lib/python3.9/site-packages/volatility3/framework/layers
21-06-07 12:14:49 volatility3.framework.configuration.requirements Level 9  IndexError - No configuration provided: plugins.List_Files.primary
21-06-07 12:14:49 volatility3.framework.configuration.requirements Level 9  Symbol table requirement not yet fulfilled: plugins.List_Files.darwin
21-06-07 12:14:49 volatility3.framework Level 6  Importing from the following paths: /home/user/.local/lib/python3.9/site-packages/volatility3/framework/layers
21-06-07 12:14:50 volatility3.framework.configuration.requirements Level 9  IndexError - No configuration provided: plugins.List_Files.primary
21-06-07 12:14:50 volatility3.framework Level 6  Importing from the following paths: /home/user/.local/lib/python3.9/site-packages/volatility3/framework/layers
21-06-07 12:14:50 volatility3.framework Level 6  Importing from the following paths: /home/user/.local/lib/python3.9/site-packages/volatility3/framework/layers
21-06-07 12:14:50 volatility3.framework.configuration.requirements Level 9  IndexError - No configuration provided: plugins.List_Files.primary.memory_layer
21-06-07 12:14:50 volatility3.framework Level 6  Importing from the following paths: /home/user/.local/lib/python3.9/site-packages/volatility3/framework/layers
21-06-07 12:14:50 volatility3.framework Level 6  Importing from the following paths: /home/user/.local/lib/python3.9/site-packages/volatility3/framework/layers
21-06-07 12:14:50 volatility3.framework Level 6  Importing from the following paths: /home/user/.local/lib/python3.9/site-packages/volatility3/framework/layers
21-06-07 12:14:50 volatility3.framework Level 6  Importing from the following paths: /home/user/.local/lib/python3.9/site-packages/volatility3/framework/layers
21-06-07 12:14:50 volatility3.framework Level 6  Importing from the following paths: /home/user/.local/lib/python3.9/site-packages/volatility3/framework/layers
21-06-07 12:14:50 volatility3.framework.interfaces.configuration Level 9  TypeError - kernel_virtual_offset requirements only accept int type: None
21-06-07 12:14:50 volatility3.framework.interfaces.configuration Level 9  TypeError - kernel_virtual_offset requirements only accept int type: None
21-06-07 12:14:50 volatility3.framework Level 6  Importing from the following paths: /home/user/.local/lib/python3.9/site-packages/volatility3/framework/layers
21-06-07 12:14:50 volatility3.framework Level 6  Importing from the following paths: /home/user/.local/lib/python3.9/site-packages/volatility3/framework/layers
21-06-07 12:14:50 volatility3.framework.configuration.requirements Level 9  Symbol table requirement not yet fulfilled: plugins.List_Files.darwin
21-06-07 12:14:50 volatility3.framework Level 6  Importing from the following paths: /home/user/.local/lib/python3.9/site-packages/volatility3/framework/layers
21-06-07 12:14:50 volatility3.framework.automagic.construct_layers Level 9  Failed on requirement: plugins.List_Files.darwin
21-06-07 12:14:50 volatility3.framework.configuration.requirements Level 9  Symbol table requirement not yet fulfilled: plugins.List_Files.darwin
21-06-07 12:14:50 volatility3.framework.automagic.construct_layers Level 9  Failed on requirement: plugins.List_Files
21-06-07 12:14:50 volatility3.framework Level 6  Importing from the following paths: /home/user/.local/lib/python3.9/site-packages/volatility3/framework/layers
21-06-07 12:14:50 volatility3.framework.automagic.stacker DEBUG    Stacked layers: ['IntelLayer', 'FileLayer']
21-06-07 12:14:50 volatility3.framework.automagic INFO     Running automagic: MacSymbolFinder
21-06-07 12:14:50 volatility3.framework.configuration.requirements Level 9  Symbol table requirement not yet fulfilled: plugins.List_Files.darwin
21-06-07 12:14:50 volatility3.framework.automagic.symbol_finder DEBUG    Identified banner: b'Darwin Kernel Version 16.7.0: Thu Jun 15 17:36:27 PDT 2017; root:xnu-3789.70.16~2/RELEASE_X86_64\x00'
21-06-07 12:14:50 volatility3.framework.automagic.symbol_finder DEBUG    Using symbol library: jar:file:/home/user/volatility3/symbols/mac.zip!Kernel_Debug_Kit_10.12.6_build_16G29.dmg.json.xz
21-06-07 12:14:52 volatility3.framework.automagic.mac Level 6  Mac find_aslr returned: 143c6000
21-06-07 12:14:52 volatility3.framework.symbols DEBUG    Unresolved reference: darwin1!vmem
21-06-07 12:14:53 volatility3.framework.symbols DEBUG    Unresolved reference: darwin1!__lck_grp__
21-06-07 12:14:53 volatility3.framework.symbols DEBUG    Unresolved reference: darwin1!IOMemoryMap
21-06-07 12:14:53 volatility3.framework.symbols DEBUG    Unresolved reference: darwin1!IOMemoryDescriptor
```

**Comment by ikelos** [comment]
Ok, well, that is stacking the intel layer correctly and does appear to be identifying the symbol library correctly and returns an aslr value.  I think I'm gonna have to hand this one to @atcuno for further analysis I'm afraid...

**Comment by ikelos** [comment]
@atcuno This one also could do with some investigation at some point please

**Comment by gnarcap** [comment]
+1 on this issue too. Haven't been able to analyze any Mac memory dumps with vol2 or vol3 yet:
```
Unsatisfied requirement plugins.PsList.primary: Memory layer for the kernel
Unsatisfied requirement plugins.PsList.darwin: Mac kernel symbols
 
A symbol table requirement was not fulfilled.  Please verify that:
    You have the correct symbol file for the requirement
    The symbol file is under the correct directory or zip file
    The symbol file is named appropriately or contains the correct banner
 
 
A translation layer requirement was not fulfilled.  Please verify that:
    A file was provided to create this layer (by -f, --single-location or by config)
    The file exists and is readable
    The necessary symbols are present and identified by volatility
Unable to validate the plugin requirements: ['plugins.PsList.primary', 'plugins.PsList.darwin']
```

**Comment by ikelos** [comment]
@gnarcap Yours suggests it doesn't find an intel image, so please open a separate issue about this.  There's diagnostics we can run to help narrow down the problem, but it'll be better to do it in a separate issue, not to cloud this one with everyy mac problem...

**Comment by atcuno** [comment]
The idlepml4_str backtrace looks fixed here: https://github.com/volatilityfoundation/volatility3/commit/b6165b439fdee399d933eb1162e845d1811a9e6a

Do we have any samples that still do not produce the pslist output?

**Comment by ikelos** [comment]
The idlepml4_str typo was fixed, but [reported](https://github.com/volatilityfoundation/volatility3/issues/515#issuecomment-855662665) as still not returning results, when results were expected.  I don't think we ever got an image that suffered from this directly.
